name: llvm
version: 0.4.0
summary: LLVM sum.
description: LLVM desc.
confinement: devmode

environment:
  C_INCLUDE_PATH: $SNAP/usr/include:$SNAP/usr/include/x86_64-linux-gnu:$SNAP/usr/lib/gcc/x86_64-linux-gnu/5/include:$SNAP/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed
  CPP_INCLUDE_PATH: $C_INCLUDE_PATH:$SNAP/usr/include/c++/5
  BISON_PKGDATADIR: $SNAP/usr/share/bison

apps:
  bash:
    command: bin/bash
  clang:
    command: usr/bin/clang
  clangpp:
    command: usr/bin/clang++
  lldb:
    command: usr/bin/lldb
  gcc:
    command: usr/bin/gcc
  gpp:
    command: usr/bin/g++
  gdb:
    command: usr/bin/gdb
  make:
    command: usr/bin/make
  cmake:
    command: usr/bin/cmake
  bison:
    command: usr/bin/bison
  flex:
    command: usr/bin/flex
  lli:
    command: usr/bin/lli
  llvm-link:
    command: usr/bin/llvm-link
parts:
  toolchain:
    plugin: copy
    files: 
      SnapToolchain.cmake: /usr/lib/x86_64-linux-gnu/cmake/
  llvm:
    plugin: make
    source: .
    build-packages:
      - git
      - cmake
      - clang
      - build-essential
      - libncurses5-dev
      - libxml2-dev
      - libedit-dev
      - swig
      - doxygen
      - graphviz
    stage-packages: 
      - bash
      - cmake
      - make
      - gcc
      - g++
      - gdb
      - bison
      - flex
      - binutils
      - libc6
      - libc6-dev
      - libgcc1
      - libgcc-5-dev
      - libstdc++6
      - libstdc++-5-dev
      - libtinfo-dev
      - zlib1g-dev
