name: llvm
version: 0.2.3
summary: LLVM sum.
description: LLVM desc.
confinement: devmode

apps:
  bash:
    command: bin/bash
  clang:
    command: usr/bin/clang
  clangpp:
    command: usr/bin/clang++
  gcc:
    command: usr/bin/gcc
  gpp:
    command: usr/bin/g++
  gdb:
    command: usr/bin/gdb
  make:
    command: usr/bin/make
  cmake:
    command: usr/bin/cmake
  bison:
    command: usr/bin/bison
  flex:
    command: usr/bin/flex
  lli:
    command: usr/bin/lli
  llvm-link:
    command: usr/bin/llvm-link
parts:
  toolchain:
    plugin: copy
    files: 
      SnapToolchain.cmake: /usr/lib/x86_64-linux-gnu/cmake/
  llvm:
    plugin: make
    source: .
    build-packages:
      - git
      - cmake
      - clang
      - build-essential
    stage-packages: 
      - bash
      - cmake
      - make
      - gcc
      - g++
      - gdb
      - bison
      - flex
      - binutils
      - libc6
      - libc6-dev
      - libgcc1
      - libgcc-5-dev
      - libstdc++-5-dev
