name: llvm
version: 7
summary: LLVM sum.
description: LLVM desc.
confinement: devmode

apps:
  clang:
    command: usr/bin/clang
  gdb:
    command: usr/bin/gdb
  make:
    command: usr/bin/make
  cmake:
    command: usr/bin/cmake
  bison:
    command: usr/bin/bison
  flex:
    command: usr/bin/flex
  lli:
    command: usr/bin/lli
  llvm-link:
    command: usr/bin/llvm-link
parts:
  llvm:
    plugin: make
    source: .
    stage-packages: [cmake,make,gdb,bison,flex]
    build-packages:
      - git
      - cmake
      - clang
      - build-essential
