name: monodevelop
version: 0.0.7
summary: .NET GNOME IDE
description: MonoDevelop is a GNOME IDE primarily designed for C# and other CLI (.NET) languages. It is the unbranded version of Xamarin Studio. This snap package is broken.
confinement: strict
grade: devel

apps:
  monodevelop:
    command: monodevelop
    plugs: [x11,home]
parts:
  monodevelop:
    plugin: nil
    stage-packages: 
     - acl
     - adduser
     - adwaita-icon-theme
     - apt
     - apt-utils
     - aspell
     - aspell-en
     - at-spi2-core
     - base-files
     - binfmt-support
     - binutils
     - build-essential
     - bzip2
     - ca-certificates
     - ca-certificates-mono
     - cli-common
     - colord
     - colord-data
     - coreutils
     - cpp
     - cpp-5
     - dbus
     - dbus-x11
     - dconf-gsettings-backend
     - dconf-service
     - debconf
     - debconf-i18n
     - debianutils
     - dictionaries-common
     - dpkg
     - dpkg-dev
     - e2fslibs
     - e2fsprogs
     - emacsen-common
     - enchant
     - fakeroot
     - fontconfig
     - fontconfig-config
     - fonts-dejavu-core
     - g++
     - g++-5
     - gcc
     - gcc-5
     - gcc-5-base
     - gcc-6-base
     - gconf-service
     - gconf-service-backend
     - gconf2
     - gconf2-common
     - glib-networking
     - glib-networking-common
     - glib-networking-services
     - gnome-icon-theme
     - gnupg
     - gpgv
     - gsettings-desktop-schemas
     - gstreamer1.0-plugins-base
     - gstreamer1.0-plugins-good
     - gstreamer1.0-x
     - hicolor-icon-theme
     - humanity-icon-theme
     - hunspell-en-us
     - ifupdown
     - init-system-helpers
     - initscripts
     - insserv
     - iproute2
     - isc-dhcp-client
     - isc-dhcp-common
     - iso-codes
     - krb5-locales
     - libaa1
     - libacl1
     - libalgorithm-diff-perl
     - libalgorithm-diff-xs-perl
     - libalgorithm-merge-perl
     - libapparmor1
     - libapt-inst2.0
     - libapt-pkg5.0
     - libart-2.0-2
     - libart2.0-cil
     - libasan2
     - libasn1-8-heimdal
     - libasound2
     - libasound2-data
     - libaspell15
     - libatk-bridge2.0-0
     - libatk1.0-0
     - libatk1.0-data
     - libatm1
     - libatomic1
     - libatspi2.0-0
     - libattr1
     - libaudit-common
     - libaudit1
     - libavahi-client3
     - libavahi-common-data
     - libavahi-common3
     - libavahi-glib1
     - libavc1394-0
     - libblkid1
     - libbonobo2-0
     - libbonobo2-common
     - libbonoboui2-0
     - libbonoboui2-common
     - libboost-filesystem1.58.0
     - libboost-system1.58.0
     - libbsd0
     - libbz2-1.0
     - libc-dev-bin
     - libc6
     - libc6-dev
     - libcaca0
     - libcairo-gobject2
     - libcairo2
     - libcanberra0
     - libcap-ng0
     - libcap2
     - libcap2-bin
     - libcapnp-0.5.3
     - libcc1-0
     - libcdparanoia0
     - libcilkrts5
     - libcolord2
     - libcolorhug2
     - libcomerr2
     - libcroco3
     - libcryptsetup4
     - libcups2
     - libdatrie1
     - libdb5.3
     - libdbus-1-3
     - libdbus-glib-1-2
     - libdconf1
     - libdevmapper1.02.1
     - libdns-export162
     - libdpkg-perl
     - libdrm-amdgpu1
     - libdrm-intel1
     - libdrm-nouveau2
     - libdrm-radeon1
     - libdrm2
     - libdv4
     - libedit2
     - libegl1-mesa
     - libelf1
     - libenchant1c2a
     - libepoxy0
     - libexif12
     - libexpat1
     - libfakeroot
     - libfdisk1
     - libffi6
     - libfile-fcntllock-perl
     - libflac8
     - libfontconfig1
     - libfontenc1
     - libfreetype6
     - libgail18
     - libgbm1
     - libgcc-5-dev
     - libgcc1
     - libgconf-2-4
     - libgconf2.0-cil
     - libgcrypt20
     - libgd3
     - libgdbm3
     - libgdiplus
     - libgdk-pixbuf2.0-0
     - libgdk-pixbuf2.0-common
     - libgeoclue0
     - libgif7
     - libgl1-mesa-dri
     - libgl1-mesa-glx
     - libglade2-0
     - libglade2.0-cil
     - libglade2.0-cil-dev
     - libglapi-mesa
     - libglib2.0-0
     - libglib2.0-cil
     - libglib2.0-cil-dev
     - libglib2.0-data
     - libgmp10
     - libgnome-2-0
     - libgnome-keyring-common
     - libgnome-keyring0
     - libgnome-vfs2.0-cil
     - libgnome2-0
     - libgnome2-bin
     - libgnome2-common
     - libgnome2.24-cil
     - libgnomecanvas2-0
     - libgnomecanvas2-common
     - libgnomeui-0
     - libgnomeui-common
     - libgnomevfs2-0
     - libgnomevfs2-common
     - libgnutls30
     - libgomp1
     - libgpg-error0
     - libgphoto2-6
     - libgphoto2-l10n
     - libgphoto2-port12
     - libgpm2
     - libgraphite2-3
     - libgssapi-krb5-2
     - libgssapi3-heimdal
     - libgstreamer-plugins-base1.0-0
     - libgstreamer-plugins-good1.0-0
     - libgstreamer1.0-0
     - libgtk-3-0
     - libgtk-3-bin
     - libgtk-3-common
     - libgtk2.0-0
     - libgtk2.0-bin
     - libgtk2.0-cil
     - libgtk2.0-cil-dev
     - libgtk2.0-common
     - libgtkspell0
     - libgudev-1.0-0
     - libgusb2
     - libharfbuzz-icu0
     - libharfbuzz0b
     - libhcrypto4-heimdal
     - libheimbase1-heimdal
     - libheimntlm0-heimdal
     - libhogweed4
     - libhunspell-1.3-0
     - libhx509-5-heimdal
     - libice6
     - libicu55
     - libidn11
     - libiec61883-0
     - libieee1284-3
     - libisc-export160
     - libisl15
     - libitm1
     - libjack-jackd2-0
     - libjavascriptcoregtk-1.0-0
     - libjbig0
     - libjpeg-turbo8
     - libjpeg8
     - libjson-glib-1.0-0
     - libjson-glib-1.0-common
     - libk5crypto3
     - libkeyutils1
     - libkmod2
     - libkrb5-26-heimdal
     - libkrb5-3
     - libkrb5support0
     - liblcms2-2
     - libldap-2.4-2
     - libllvm3.8
     - liblocale-gettext-perl
     - liblsan0
     - libltdl7
     - liblz4-1
     - liblzma5
     - libmirclient9
     - libmircommon7
     - libmircore1
     - libmirprotobuf3
     - libmnl0
     - libmono-2.0-dev
     - libmono-accessibility4.0-cil
     - libmono-c5-1.1-cil
     - libmono-cairo4.0-cil
     - libmono-cecil-private-cil
     - libmono-cil-dev
     - libmono-codecontracts4.0-cil
     - libmono-compilerservices-symbolwriter4.0-cil
     - libmono-corlib4.5-cil
     - libmono-cscompmgd0.0-cil
     - libmono-csharp4.0c-cil
     - libmono-custommarshalers4.0-cil
     - libmono-data-tds4.0-cil
     - libmono-db2-1.0-cil
     - libmono-debugger-soft4.0a-cil
     - libmono-http4.0-cil
     - libmono-i18n-cjk4.0-cil
     - libmono-i18n-mideast4.0-cil
     - libmono-i18n-other4.0-cil
     - libmono-i18n-rare4.0-cil
     - libmono-i18n-west4.0-cil
     - libmono-i18n4.0-all
     - libmono-i18n4.0-cil
     - libmono-ldap4.0-cil
     - libmono-management4.0-cil
     - libmono-messaging-rabbitmq4.0-cil
     - libmono-messaging4.0-cil
     - libmono-microsoft-build-engine4.0-cil
     - libmono-microsoft-build-framework4.0-cil
     - libmono-microsoft-build-tasks-v4.0-4.0-cil
     - libmono-microsoft-build-utilities-v4.0-4.0-cil
     - libmono-microsoft-build4.0-cil
     - libmono-microsoft-csharp4.0-cil
     - libmono-microsoft-visualc10.0-cil
     - libmono-microsoft-web-infrastructure1.0-cil
     - libmono-oracle4.0-cil
     - libmono-parallel4.0-cil
     - libmono-peapi4.0a-cil
     - libmono-posix4.0-cil
     - libmono-rabbitmq4.0-cil
     - libmono-relaxng4.0-cil
     - libmono-security4.0-cil
     - libmono-sharpzip4.84-cil
     - libmono-simd4.0-cil
     - libmono-smdiagnostics0.0-cil
     - libmono-sqlite4.0-cil
     - libmono-system-componentmodel-composition4.0-cil
     - libmono-system-componentmodel-dataannotations4.0-cil
     - libmono-system-configuration-install4.0-cil
     - libmono-system-configuration4.0-cil
     - libmono-system-core4.0-cil
     - libmono-system-data-datasetextensions4.0-cil
     - libmono-system-data-entity4.0-cil
     - libmono-system-data-linq4.0-cil
     - libmono-system-data-services-client4.0-cil
     - libmono-system-data-services4.0-cil
     - libmono-system-data4.0-cil
     - libmono-system-design4.0-cil
     - libmono-system-drawing-design4.0-cil
     - libmono-system-drawing4.0-cil
     - libmono-system-dynamic4.0-cil
     - libmono-system-enterpriseservices4.0-cil
     - libmono-system-identitymodel-selectors4.0-cil
     - libmono-system-identitymodel4.0-cil
     - libmono-system-io-compression-filesystem4.0-cil
     - libmono-system-io-compression4.0-cil
     - libmono-system-json-microsoft4.0-cil
     - libmono-system-json4.0-cil
     - libmono-system-ldap-protocols4.0-cil
     - libmono-system-ldap4.0-cil
     - libmono-system-management4.0-cil
     - libmono-system-messaging4.0-cil
     - libmono-system-net-http-formatting4.0-cil
     - libmono-system-net-http-webrequest4.0-cil
     - libmono-system-net-http4.0-cil
     - libmono-system-net4.0-cil
     - libmono-system-numerics4.0-cil
     - libmono-system-reactive-core2.2-cil
     - libmono-system-reactive-debugger2.2-cil
     - libmono-system-reactive-experimental2.2-cil
     - libmono-system-reactive-interfaces2.2-cil
     - libmono-system-reactive-linq2.2-cil
     - libmono-system-reactive-observable-aliases0.0-cil
     - libmono-system-reactive-platformservices2.2-cil
     - libmono-system-reactive-providers2.2-cil
     - libmono-system-reactive-runtime-remoting2.2-cil
     - libmono-system-reactive-windows-forms2.2-cil
     - libmono-system-reactive-windows-threading2.2-cil
     - libmono-system-runtime-caching4.0-cil
     - libmono-system-runtime-durableinstancing4.0-cil
     - libmono-system-runtime-serialization-formatters-soap4.0-cil
     - libmono-system-runtime-serialization4.0-cil
     - libmono-system-runtime4.0-cil
     - libmono-system-security4.0-cil
     - libmono-system-servicemodel-activation4.0-cil
     - libmono-system-servicemodel-discovery4.0-cil
     - libmono-system-servicemodel-internals0.0-cil
     - libmono-system-servicemodel-routing4.0-cil
     - libmono-system-servicemodel-web4.0-cil
     - libmono-system-servicemodel4.0a-cil
     - libmono-system-serviceprocess4.0-cil
     - libmono-system-threading-tasks-dataflow4.0-cil
     - libmono-system-transactions4.0-cil
     - libmono-system-web-abstractions4.0-cil
     - libmono-system-web-applicationservices4.0-cil
     - libmono-system-web-dynamicdata4.0-cil
     - libmono-system-web-extensions-design4.0-cil
     - libmono-system-web-extensions4.0-cil
     - libmono-system-web-http-selfhost4.0-cil
     - libmono-system-web-http-webhost4.0-cil
     - libmono-system-web-http4.0-cil
     - libmono-system-web-mvc3.0-cil
     - libmono-system-web-razor2.0-cil
     - libmono-system-web-routing4.0-cil
     - libmono-system-web-services4.0-cil
     - libmono-system-web-webpages-deployment2.0-cil
     - libmono-system-web-webpages-razor2.0-cil
     - libmono-system-web-webpages2.0-cil
     - libmono-system-web4.0-cil
     - libmono-system-windows-forms-datavisualization4.0a-cil
     - libmono-system-windows-forms4.0-cil
     - libmono-system-windows4.0-cil
     - libmono-system-xaml4.0-cil
     - libmono-system-xml-linq4.0-cil
     - libmono-system-xml-serialization4.0-cil
     - libmono-system-xml4.0-cil
     - libmono-system4.0-cil
     - libmono-tasklets4.0-cil
     - libmono-webbrowser4.0-cil
     - libmono-webmatrix-data4.0-cil
     - libmono-windowsbase4.0-cil
     - libmono-xbuild-tasks4.0-cil
     - libmonoboehm-2.0-1
     - libmonoboehm-2.0-dev
     - libmount1
     - libmpc3
     - libmpfr4
     - libmpx0
     - libncurses5
     - libncursesw5
     - libnettle6
     - libnunit-cil-dev
     - libnunit-console-runner2.6.3-cil
     - libnunit-core-interfaces2.6.3-cil
     - libnunit-core2.6.3-cil
     - libnunit-framework2.6.3-cil
     - libnunit-mocks2.6.3-cil
     - libnunit-util2.6.3-cil
     - libogg0
     - libopus0
     - liborbit-2-0
     - liborc-0.4-0
     - libp11-kit0
     - libpam-modules
     - libpam-modules-bin
     - libpam-runtime
     - libpam-systemd
     - libpam0g
     - libpango-1.0-0
     - libpangocairo-1.0-0
     - libpangoft2-1.0-0
     - libpciaccess0
     - libpcre3
     - libperl5.22
     - libpipeline1
     - libpixman-1-0
     - libpng12-0
     - libpolkit-agent-1-0
     - libpolkit-backend-1-0
     - libpolkit-gobject-1-0
     - libpopt0
     - libprocps4
     - libprotobuf-lite9v5
     - libproxy1v5
     - libquadmath0
     - libraw1394-11
     - libreadline6
     - librest-0.7-0
     - libroken18-heimdal
     - librsvg2-2
     - librsvg2-common
     - libsamplerate0
     - libsane
     - libsane-common
     - libsasl2-2
     - libsasl2-modules
     - libsasl2-modules-db
     - libseccomp2
     - libsecret-1-0
     - libsecret-common
     - libselinux1
     - libsemanage-common
     - libsemanage1
     - libsepol1
     - libshout3
     - libslang2
     - libsm6
     - libsmartcols1
     - libsoup-gnome2.4-1
     - libsoup2.4-1
     - libspeex1
     - libsqlite3-0
     - libss2
     - libssl1.0.0
     - libstdc++-5-dev
     - libstdc++6
     - libsystemd0
     - libtag1v5
     - libtag1v5-vanilla
     - libtasn1-6
     - libtdb1
     - libtext-charwidth-perl
     - libtext-iconv-perl
     - libtext-wrapi18n-perl
     - libthai-data
     - libthai0
     - libtheora0
     - libtiff5
     - libtinfo5
     - libtsan0
     - libtxc-dxtn-s2tc0
     - libubsan0
     - libudev1
     - libusb-0.1-4
     - libusb-1.0-0
     - libustr-1.0-1
     - libutempter0
     - libuuid1
     - libv4l-0
     - libv4lconvert0
     - libvisual-0.4-0
     - libvorbis0a
     - libvorbisenc2
     - libvorbisfile3
     - libvpx3
     - libwavpack1
     - libwayland-client0
     - libwayland-cursor0
     - libwayland-egl1-mesa
     - libwayland-server0
     - libwebkit1.1-cil
     - libwebkitgtk-1.0-0
     - libwebkitgtk-1.0-common
     - libwebp5
     - libwind0-heimdal
     - libx11-6
     - libx11-data
     - libx11-xcb1
     - libxau6
     - libxaw7
     - libxcb-dri2-0
     - libxcb-dri3-0
     - libxcb-glx0
     - libxcb-present0
     - libxcb-render0
     - libxcb-shape0
     - libxcb-shm0
     - libxcb-sync1
     - libxcb-xfixes0
     - libxcb1
     - libxcomposite1
     - libxcursor1
     - libxdamage1
     - libxdmcp6
     - libxext6
     - libxfixes3
     - libxft2
     - libxi6
     - libxinerama1
     - libxkbcommon0
     - libxml2
     - libxmu6
     - libxmuu1
     - libxpm4
     - libxrandr2
     - libxrender1
     - libxshmfence1
     - libxslt1.1
     - libxt6
     - libxtables11
     - libxtst6
     - libxv1
     - libxxf86dga1
     - libxxf86vm1
     - linux-libc-dev
     - lsb-base
     - make
     - manpages
     - manpages-dev
     - mawk
     - mono-4.0-gac
     - mono-csharp-shell
     - mono-devel
     - mono-gac
     - mono-mcs
     - mono-runtime
     - mono-runtime-common
     - mono-runtime-sgen
     - mono-xbuild
     - monodevelop
     - monodoc-base
     - monodoc-browser
     - monodoc-manual
     - mount
     - multiarch-support
     - netbase
     - openssl
     - passwd
     - patch
     - perl
     - perl-base
     - perl-modules-5.22
     - pkg-config
     - policykit-1
     - procps
     - psmisc
     - readline-common
     - rename
     - sed
     - sensible-utils
     - sgml-base
     - shared-mime-info
     - sound-theme-freedesktop
     - systemd
     - systemd-sysv
     - sysv-rc
     - sysvinit-utils
     - tar
     - ubuntu-keyring
     - ubuntu-mono
     - ucf
     - udev
     - util-linux
     - uuid-runtime
     - x11-common
     - x11-utils
     - xbitmaps
     - xdg-user-dirs
     - xkb-data
     - xml-core
     - xterm
     - xz-utils
     - zlib1g
