name: simavr
version: 0.0.1
summary: A lean and mean Atmel AVR simulator for linux
description: simavr is a new AVR simulator for linux, or any platform that uses avr-gcc. It uses avr-gcc's own register definition to simplify creating new targets for supported AVR devices. The core was made to be small and compact, and hackable so allow quick prototyping of an AVR project. The AVR core is now stable for use with parts with <= 128KB flash, and with preliminary support for the bigger parts. The simulator loads ELF files directly, and there is even a way to specify simulation parameters directly in the emulated code using an .elf section. You can also load multipart HEX files. 
confinement: strict

apps:
  simavr:
    command: simavr
parts:
  simavr:
    plugin: make
    source: git@github.com:buserror/simavr.git
    source-tag: v1.3
    build-packages:
     - build-essential
     - libelf-dev
     - freeglut3-dev
